#include "ip.h"
#include "icmp.h"
#include "arpcache.h"
#include "rtable.h"
#include "arp.h"

// #include "log.h"

#include <stdio.h>
#include <stdlib.h>

// initialize ip header 
void ip_init_hdr(struct iphdr *ip, u32 saddr, u32 daddr, u16 len, u8 proto)
{
	ip->version = 4;
	ip->ihl = 5;
	ip->tos = 0;
	ip->tot_len = htons(len);
	ip->id = rand();
	ip->frag_off = htons(IP_DF);
	ip->ttl = DEFAULT_TTL;
	ip->protocol = proto;
	ip->saddr = htonl(saddr);
	ip->daddr = htonl(daddr);
	ip->checksum = ip_checksum(ip);
}

// lookup in the routing table, to find the entry with the same and longest prefix.
// the input address is in host byte order
rt_entry_t *longest_prefix_match(u32 dst)
{
	rt_entry_t *res = NULL;
	rt_entry_t *entry;
	list_for_each_entry(entry, &rtable, list) {
		if ((dst & entry->mask) == (entry->dest & entry->mask)) {
			if (!res || entry->mask > res->mask) res = entry;
		}
	}
	return res;
}

// send IP packet
//
// Different from forwarding packet, ip_send_packet sends packet generated by
// router itself. This function is used to send ICMP packets.
void ip_send_packet(char *packet, int len)
{
	// Do Nothing
	struct ether_header *eh = (struct ether_header *) packet;
	struct iphdr *iph = (struct iphdr *) (packet + ETHER_HDR_SIZE);

	iface_info_t *iface;
	list_for_each_entry(iface, &instance->iface_list, list) {
		if (iface->ip == ntohl(iph->saddr)) break;
	}

	if (!iface) {
		printf("ip_send_packet: cannot find corresponding iface!\n");
		return;
	}
	
	iface_send_packet_by_arp(iface, ntohl(iph->daddr), packet, len);
}
